name: JustWorld
version: '0.0.3'
main: dev.meyba.justWorld.JustWorld
api-version: '1.21'
authors: [ Meyba._., Jezevcik20 ]
description: Just a world plugin.

commands:
  world:
    description: Main world management command
    usage: /world <create|delete|load|unload|tp|list|info|pregen|portal>
    aliases: [w, jw]
    permission: justworld.admin
    permission-message: "You don't have permission to use this command!"
  justworld:
    description: Show plugin info and statistics
    usage: /justworld [reload]
    aliases: [jworld]
    permission: justworld.admin
    permission-message: "You don't have permission to use this command!"
permissions:
  justworld.admin:
    description: Access to all JustWorld commands
    default: op
  justworld.create:
    description: Create new worlds
    default: op
  justworld.delete:
    description: Delete worlds
    default: op
  justworld.load:
    description: Load worlds
    default: op
  justworld.unload:
    description: Unload worlds
    default: op
  justworld.teleport:
    description: Teleport to worlds
    default: op
  justworld.list:
    description: List all worlds
    default: op
  justworld.info:
    description: View world information
    default: op
  justworld.pregen:
    description: Pregenerate world chunks
    default: op
  justworld.portal:
    description: Manage portal links
    default: op
  justworld.inventory:
    description: Bypass per-world inventory
    default: op
